linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - funlen
    - godox

issues:
  exclude-use-default: false
  exclude-rules:
    - text: "StreamID redeclared"
      linters:
        - typecheck
    - text: "other declaration of StreamID"
      linters:
        - typecheck
